
import "./globals.css";
import { Box, ThemeProvider } from "@mui/material";
import theme from "@/theme";
import AppLayout from "./AppLayout";

export const metadata = {
  title: "MemoryArch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ overflowX: "hidden" }}>
        <ThemeProvider theme={theme}>
          <AppLayout>
            <Box
              // sx={{ overflowX: "hidden", height: "100vh" }}
              sx={{
                overflowX: "hidden",
                // paddingBottom: {
                //   xs: "-20px", // on screens <600px
                //   sm: "-20px", // on larger screens
                // },
              }}
            >
              <div className="zoomed-layout">{children}</div>
            </Box>
          </AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
