// import "./globals.css";
// import { Box, ThemeProvider } from "@mui/material";
// import theme from "@/src/theme";
// import AppLayout from "./AppLayout";

// export const metadata = {
//   title: "MemoryArch",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}

//         <link
//           href="https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,600,700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body>
//         <ThemeProvider theme={theme}>
//           <AppLayout>
//             {/* <Box
//               width="100%"
//               maxWidth="1580px"
//               margin="0 auto"
//               sx={{
//                 overflowX: "hidden",
//                 backgroundColor: "#fff",
//               }}
//             >
//               {" "} */}
//             <Box maxWidth={"1140px"} padding={"0 12px"} margin={"0 auto"}>
//               {children}
//             </Box>
//             {/* </Box> */}
//           </AppLayout>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import { Box, ThemeProvider } from "@mui/material";
import theme from "@/src/theme";
import AppLayout from "./AppLayout";

export const metadata = {
  title: "MemoryArch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ overflowX: "hidden" }}>
        <ThemeProvider theme={theme}>
          <AppLayout>
            <Box sx={{ overflowX: "hidden", height: "100vh" }}>
              <div className="zoomed-layout">{children}</div>
            </Box>
          </AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
